"""Position validation — the gate between recognition and Stockfish.

Phase 7 of the spec:

    Before sending a position to Stockfish:
      * Validate FEN.
      * Ensure exactly one king exists for each side.
      * Validate side to move.
      * Reject obviously impossible/invalid positions.
      * Prevent garbage generated by incorrect recognition from Stockfish.

    If the position is invalid:
        Position invalid. Rechecking recognition...
    Do not run Stockfish.

    Where practical, distinguish between:
      * invalid FEN
      * low-confidence recognition
      * board detection failure
      * temporary visual change
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum

import chess

# Text mandated by the spec. Tests assert on these exact strings.
INVALID_POSITION_MESSAGE = "Position invalid. Rechecking recognition..."
BOARD_DETECTION_MESSAGE = "Board detection failed. Please select the region again."
TEMPORARY_VISUAL_MESSAGE = "Temporary visual change. Position unchanged."
LOW_CONFIDENCE_HEADER = "Position uncertain. Low-confidence detection:"
LOW_CONFIDENCE_FOOTER = "Please capture again."

# Detections that barely cleared YOLO's own cutoff are not worth handing to
# the engine when a structural check would otherwise let them through.
# Configurable per the spec; 0 disables the check. The spec's own example of a
# doubtful detection is 0.54, and correct recognitions measured on the test
# fixture sit above 0.88, so 0.60 separates the two with margin.
DEFAULT_MIN_SQUARE_CONFIDENCE = 0.60


class ErrorKind(Enum):
    """Why a position was rejected."""

    INVALID_FEN = "invalid_fen"
    INVALID_POSITION = "invalid_position"
    LOW_CONFIDENCE = "low_confidence"
    BOARD_DETECTION_FAILURE = "board_detection_failure"
    TEMPORARY_VISUAL_CHANGE = "temporary_visual_change"


# python-chess already spells out *why* a parsed position is impossible.
_STATUS_DETAILS: dict[int, str] = {
    int(chess.Status.NO_WHITE_KING): "exactly one white king is required",
    int(chess.Status.NO_BLACK_KING): "exactly one black king is required",
    int(chess.Status.TOO_MANY_KINGS): "exactly one king per side is required",
    int(chess.Status.TOO_MANY_WHITE_PAWNS): "more than 8 white pawns",
    int(chess.Status.TOO_MANY_BLACK_PAWNS): "more than 8 black pawns",
    int(chess.Status.PAWNS_ON_BACKRANK): "a pawn stands on rank 1 or 8",
    int(chess.Status.TOO_MANY_WHITE_PIECES): "more than 16 white pieces",
    int(chess.Status.TOO_MANY_BLACK_PIECES): "more than 16 black pieces",
    int(chess.Status.BAD_CASTLING_RIGHTS): "castling rights are impossible",
    int(chess.Status.INVALID_EP_SQUARE): "the en passant square is impossible",
    int(chess.Status.OPPOSITE_CHECK): "the side not to move is already in check",
    int(chess.Status.EMPTY): "the position contains no pieces",
    int(chess.Status.RACE_CHECK): "antichess check flag is set",
    int(chess.Status.RACE_OVER): "the antichess race is already over",
    int(chess.Status.RACE_MATERIAL): "antichess material flag is set",
    int(chess.Status.TOO_MANY_CHECKERS): "more than two pieces give check",
    int(chess.Status.IMPOSSIBLE_CHECK): "the check is impossible",
}


@dataclass(frozen=True)
class ValidationResult:
    """Outcome of validating a recognized position."""

    ok: bool
    kind: ErrorKind | None = None
    message: str = ""
    detail: str = ""
    fen: str | None = None
    board: chess.Board | None = None

    @property
    def is_valid(self) -> bool:
        return self.ok

    @property
    def display(self) -> str:
        """Full text to show the user. Empty for a valid position."""
        if self.ok:
            return ""
        parts = [self.message] if self.message else []
        if self.detail:
            parts.append(self.detail)
        if self.kind is ErrorKind.LOW_CONFIDENCE:
            parts.append(LOW_CONFIDENCE_FOOTER)
        return "\n".join(parts)

    def __bool__(self) -> bool:
        return self.ok


def _fail(
    kind: ErrorKind,
    message: str = INVALID_POSITION_MESSAGE,
    detail: str = "",
    fen: str | None = None,
    board: chess.Board | None = None,
) -> ValidationResult:
    return ValidationResult(
        ok=False,
        kind=kind,
        message=message,
        detail=detail,
        fen=fen,
        board=board,
    )


def board_detection_failure(detail: str = "") -> ValidationResult:
    """The board geometry could not be obtained from this frame."""
    return _fail(ErrorKind.BOARD_DETECTION_FAILURE, BOARD_DETECTION_MESSAGE, detail)


def temporary_visual_change(detail: str = "") -> ValidationResult:
    """Pixels moved but the frame came back to the last known position."""
    return _fail(ErrorKind.TEMPORARY_VISUAL_CHANGE, TEMPORARY_VISUAL_MESSAGE, detail)


def _describe_square(index: int, symbol: str, confidence: float) -> str:
    file_index = index % 8
    rank_index = 7 - (index // 8)  # index 0 is a8
    square = chess.square_name(chess.square(file_index, rank_index))
    piece = chess.Piece.from_symbol(symbol)
    color = "white" if piece.color == chess.WHITE else "black"
    name = chess.piece_name(piece.piece_type)
    return f"{square} — {color} {name} — {confidence:.2f}"


def _worst_confident_square(
    squares: Sequence[str],
    confidences: Sequence[float],
    threshold: float,
) -> str | None:
    """Describe the least confident occupied square, if it is below threshold."""
    worst_index = -1
    worst_confidence = threshold
    for index, symbol in enumerate(squares):
        if symbol == ".":
            continue
        if index >= len(confidences):
            break
        confidence = float(confidences[index])
        if confidence < worst_confidence:
            worst_confidence = confidence
            worst_index = index
    if worst_index < 0:
        return None
    return _describe_square(worst_index, squares[worst_index], worst_confidence)


def validate_fen(
    fen: str,
    *,
    squares: Sequence[str] | None = None,
    confidences: Sequence[float] | None = None,
    side_to_move: str | None = None,
    min_square_confidence: float = DEFAULT_MIN_SQUARE_CONFIDENCE,
) -> ValidationResult:
    """Validate a FEN before it is allowed to reach Stockfish.

    ``squares`` and ``confidences`` are the recognizer output that produced
    ``fen`` (64 entries each); when both are given the least confident
    occupied square is checked against ``min_square_confidence``.
    """
    if fen is None or not str(fen).strip():
        return _fail(ErrorKind.INVALID_FEN, detail="the FEN string is empty")

    try:
        board = chess.Board(str(fen).strip())
    except ValueError as exc:
        return _fail(ErrorKind.INVALID_FEN, detail=str(exc))

    if side_to_move is not None and side_to_move not in ("w", "b"):
        return _fail(
            ErrorKind.INVALID_FEN,
            detail=f"side to move must be 'w' or 'b', got {side_to_move!r}",
            fen=fen,
            board=board,
        )
    turn_letter = "w" if board.turn else "b"
    if side_to_move is not None and side_to_move != turn_letter:
        return _fail(
            ErrorKind.INVALID_FEN,
            detail=f"side to move {side_to_move!r} contradicts the FEN ({turn_letter!r})",
            fen=fen,
            board=board,
        )

    status = int(board.status())
    if status != 0:
        details = [
            text for flag, text in _STATUS_DETAILS.items() if status & flag
        ]
        return _fail(
            ErrorKind.INVALID_POSITION,
            detail="; ".join(details) or f"position status flags {status}",
            fen=fen,
            board=board,
        )

    if squares is not None and confidences is not None and min_square_confidence > 0.0:
        detail = _worst_confident_square(squares, confidences, min_square_confidence)
        if detail is not None:
            return _fail(
                ErrorKind.LOW_CONFIDENCE,
                LOW_CONFIDENCE_HEADER,
                detail=detail,
                fen=fen,
                board=board,
            )

    return ValidationResult(ok=True, fen=fen, board=board)
